### ISSUE TITLE
Chart template error due to hard coded value

### ISSUE THREAD

**Issue by tonygilkerson** [NVIDIA/gpu-feature-discovery#39]
I found a hard coded value [here](https://github.com/NVIDIA/gpu-feature-discovery/blob/main/deployments/helm/gpu-feature-discovery/templates/daemonset.yml#L79) in the chart.  

I think you want this instead

```yaml
# Before (bug)
{{- if typeIs "bool" .Values.nfd.enableNodeFeatureApi }}
  - name: GFD_USE_NODE_FEATURE_API
    value: "true" #<--- Hard code
{{- end }}

# After
{{- if typeIs "bool" .Values.nfd.enableNodeFeatureApi }}
  - name: GFD_USE_NODE_FEATURE_API
    value: {{ .Values.nfd.enableNodeFeatureApi | quote }}
{{- end }}
```
