### ISSUE TITLE
WSL2 support

### ISSUE THREAD

**Issue by davidshen84** [NVIDIA/gpu-feature-discovery#64]
Hi,

My k8s master node lives in a WSL2 instance. I configured the Nvidia container runtime and I am able to access the GPU in my WSL2 environment.

I installed **gfd** using the `nvidia-device-plugin` helm chart with the following values:

```yaml
config:
  map:
    default: |
      version: v1
      flags:
        migStrategy: none
      sharing:
        timeSlicing:
          renameByDefault: true
          failRequestsGreaterThanOne: false
          resources:
            - name: nvidia.com/gpu
              replicas: 4      
  default: "default"

runtimeClassName: nvidia

image:
  repository: registry.gitlab.com/nvidia/kubernetes/device-plugin/staging/k8s-device-plugin
  tag: "8b416016"

gfd:
  enabled: true
```

This enables the sub-chart of **gfd**. Regarding the **8b416016** tag, please refer to https://github.com/NVIDIA/k8s-device-plugin/issues/332.

After the chart is applied, I can see a `nvdp-node-feature-discovery-master` pod and a `nvdp-node-feature-discovery-worker` pod are created and running. No apparent errors were noticed in either of the pods. However, there's no trace of the `nvdp-gpu-feature-discovery` pod.

I can confirm that I can run pods with GPU resource requests.

I have another Gentoo Linux machine that joins my k8s cluster as an agent node. Up on joining, the following pods are deployed to this node and the GPU feature labels are added to this node.

- nvdp-gpu-feature-discovery
- nvdp-node-feature-discovery-worker

I think the **nfd** master pod believes the WSL 2 node does not support GPU and decided not to deploy the **gfd** pod to this node at all.
